package com.xuexiang.view.draglayoutexpand;

public class Cheeses {
    public static final String[] sCheeseStrings = {
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
    };
    public static final String[] NAMES = {
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
            "Johnny", "Johnny", "Johnny", "Johnny", "Johnny",
    };
}